const GRAPH_ERROR_CODES = {
  INVALID_REQUEST: "INVALID_REQUEST",
  TASK_ANALYSIS_FAILURE: "TASK_ANALYSIS_FAILURE",
  PLANNING_FAILURE: "PLANNING_FAILURE",
  TOOL_SELECTION_FAILURE: "TOOL_SELECTION_FAILURE",
  TOOL_EXECUTION_FAILURE: "TOOL_EXECUTION_FAILURE",
  EVIDENCE_FAILURE: "EVIDENCE_FAILURE",
  VALIDATION_FAILURE: "VALIDATION_FAILURE",
  REASONING_FAILURE: "REASONING_FAILURE",
  RESPONSE_FAILURE: "RESPONSE_FAILURE",
  APPROVAL_REQUIRED: "APPROVAL_REQUIRED",
  APPROVAL_REJECTED: "APPROVAL_REJECTED",
  CHECKPOINT_FAILURE: "CHECKPOINT_FAILURE",
  GRAPH_TIMEOUT: "GRAPH_TIMEOUT",
  GRAPH_MAX_STEPS: "GRAPH_MAX_STEPS",
  GRAPH_MAX_TOOL_CALLS: "GRAPH_MAX_TOOL_CALLS",
  INTERNAL_ERROR: "INTERNAL_ERROR",
};

class GraphRuntimeError extends Error {
  constructor(code, message, details = {}) {
    super(message);
    this.name = "GraphRuntimeError";
    this.code = code;
    this.details = details;
  }
}

module.exports = {
  GRAPH_ERROR_CODES,
  GraphRuntimeError,
};
