const DEFAULT_GRAPH_CONFIG = {
  MAX_GRAPH_STEPS: 20,
  MAX_TOOL_CALLS: 10,
  MAX_TOOL_RETRIES: 2,
  GRAPH_TIMEOUT_MS: 30000,
  CHECKPOINT_RETENTION: 100,
};

module.exports = {
  DEFAULT_GRAPH_CONFIG,
};
