import type { Role } from "../types/domain";

export const routeAccess: Record<string, Role[]> = {
  "/dashboard": [
    "Patient",
    "Doctor",
    "Nurse",
    "Receptionist",
    "Healthcare Administrator",
  ],
  "/patients": ["Doctor", "Nurse", "Receptionist", "Healthcare Administrator"],
  "/patients/search": [
    "Doctor",
    "Nurse",
    "Receptionist",
    "Healthcare Administrator",
  ],
  "/patients/:patientId": [
    "Patient",
    "Doctor",
    "Nurse",
    "Receptionist",
    "Healthcare Administrator",
  ],
  "/appointments": [
    "Patient",
    "Doctor",
    "Nurse",
    "Receptionist",
    "Healthcare Administrator",
  ],
  "/appointments/:appointmentId": [
    "Patient",
    "Doctor",
    "Nurse",
    "Receptionist",
    "Healthcare Administrator",
  ],
  "/providers": ["Doctor", "Receptionist", "Healthcare Administrator"],
  "/medical-records": ["Patient", "Doctor", "Nurse", "Healthcare Administrator"],
  "/prescriptions": [
    "Patient",
    "Doctor",
    "Nurse",
    "Healthcare Administrator",
  ],
  "/billing-insurance": [
    "Patient",
    "Receptionist",
    "Healthcare Administrator",
  ],
  "/claims": ["Receptionist", "Healthcare Administrator"],
  "/notifications": [
    "Patient",
    "Doctor",
    "Nurse",
    "Receptionist",
    "Healthcare Administrator",
  ],
  "/reports": ["Doctor", "Receptionist", "Healthcare Administrator"],
  "/admin": ["Healthcare Administrator"],
  "/profile": [
    "Patient",
    "Doctor",
    "Nurse",
    "Receptionist",
    "Healthcare Administrator",
  ],
  "/settings": [
    "Patient",
    "Doctor",
    "Nurse",
    "Receptionist",
    "Healthcare Administrator",
  ],
  "/help": [
    "Patient",
    "Doctor",
    "Nurse",
    "Receptionist",
    "Healthcare Administrator",
  ],
  "/search": ["Doctor", "Nurse", "Receptionist", "Healthcare Administrator"],
};
