import type { Role } from "../types/domain";

export const routeAccess: Record<string, Role[]> = {
  "/dashboard": [
    "Patient",
    "Doctor",
    "Nurse",
    "Receptionist",
    "Healthcare Administrator",
  ],
  "/patients": ["Doctor", "Nurse", "Receptionist", "Healthcare Administrator"],
  "/patients/search": [
    "Doctor",
    "Nurse",
    "Receptionist",
    "Healthcare Administrator",
  ],
  "/patients/:patientId": [
    "Patient",
    "Doctor",
    "Nurse",
    "Receptionist",
    "Healthcare Administrator",
  ],
  "/appointments": [
    "Patient",
    "Doctor",
    "Nurse",
    "Receptionist",
    "Healthcare Administrator",
  ],
  "/appointments/:appointmentId": [
    "Patient",
    "Doctor",
    "Nurse",
    "Receptionist",
    "Healthcare Administrator",
  ],
  "/providers": ["Doctor", "Receptionist", "Healthcare Administrator"],
  "/medical-records": ["Patient", "Doctor", "Nurse", "Healthcare Administrator"],
  "/prescriptions": [
    "Patient",
    "Doctor",
    "Nurse",
    "Healthcare Administrator",
  ],
  "/billing-insurance": [
    "Patient",
    "Receptionist",
    "Healthcare Administrator",
  ],
  "/claims": ["Receptionist", "Healthcare Administrator"],
  "/notifications": [
    "Patient",
    "Doctor",
    "Nurse",
    "Receptionist",
    "Healthcare Administrator",
  ],
  "/reports": ["Doctor", "Receptionist", "Healthcare Administrator"],
  "/admin": ["Healthcare Administrator"],
  "/profile": [
    "Patient",
    "Doctor",
    "Nurse",
    "Receptionist",
    "Healthcare Administrator",
  ],
  "/settings": [
    "Patient",
    "Doctor",
    "Nurse",
    "Receptionist",
    "Healthcare Administrator",
  ],
  "/help": [
    "Patient",
    "Doctor",
    "Nurse",
    "Receptionist",
    "Healthcare Administrator",
  ],
  "/search": ["Doctor", "Nurse", "Receptionist", "Healthcare Administrator"],
  "/jira": ["Doctor", "Nurse", "Receptionist", "Healthcare Administrator"],
  "/jira/dashboard": [
    "Doctor",
    "Nurse",
    "Receptionist",
    "Healthcare Administrator",
  ],
  "/jira/issues": ["Doctor", "Nurse", "Receptionist", "Healthcare Administrator"],
  "/jira/issues/:issueKey": [
    "Doctor",
    "Nurse",
    "Receptionist",
    "Healthcare Administrator",
  ],
  "/jira/test-cases": [
    "Doctor",
    "Nurse",
    "Receptionist",
    "Healthcare Administrator",
  ],
  "/jira/defects": [
    "Doctor",
    "Nurse",
    "Receptionist",
    "Healthcare Administrator",
  ],
  "/jira/board": ["Doctor", "Nurse", "Receptionist", "Healthcare Administrator"],
  "/confluence": [
    "Patient",
    "Doctor",
    "Nurse",
    "Receptionist",
    "Healthcare Administrator",
  ],
  "/confluence/spaces": ["Doctor", "Nurse", "Receptionist", "Healthcare Administrator"],
  "/confluence/pages": ["Doctor", "Nurse", "Receptionist", "Healthcare Administrator"],
  "/confluence/pages/:pageId": [
    "Doctor",
    "Nurse",
    "Receptionist",
    "Healthcare Administrator",
  ],
  "/confluence/search": [
    "Patient",
    "Doctor",
    "Nurse",
    "Receptionist",
    "Healthcare Administrator",
  ],
  "/traceability": ["Doctor", "Nurse", "Receptionist", "Healthcare Administrator"],
  "/knowledge": [
    "Patient",
    "Doctor",
    "Nurse",
    "Receptionist",
    "Healthcare Administrator",
  ],
  "/knowledge/evaluation": [
    "Patient",
    "Doctor",
    "Nurse",
    "Receptionist",
    "Healthcare Administrator",
  ],
  "/mcp": ["Doctor", "Nurse", "Receptionist", "Healthcare Administrator"],
  "/agent": ["Doctor", "Nurse", "Receptionist", "Healthcare Administrator"],
};
